# Generated by Django 4.2.1 on 2023-05-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kun_uz', '0002_day_new_piece'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=10000)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kun_uz.article')),
            ],
        ),
        migrations.CreateModel(
            name='Actual_piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kun_uz.actual')),
            ],
        ),
    ]
