# Generated by Django 4.2.1 on 2023-05-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kun_uz', '0003_article_piece_actual_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_piece',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bisnes_new_piece',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
